"""
Django settings for newspaper project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-+8r9jqr2c(b4_nme5th^f_dz+wwko13mlrmwu&ou#t#1!$ezwt"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "daphne",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "drf_spectacular",
    "channels",
    "django_ckeditor_5",
    "blog",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "newspaper.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "newspaper.wsgi.application"
ASGI_APPLICATION = "newspaper.asgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
CKEDITOR_5_CONFIGS = {
    "default": {
        "toolbar": [
            "heading",
            "|",
            "bold",
            "italic",
            "link",
            "bulletedList",
            "numberedList",
            "blockQuote",
            "imageUpload",
            "insertTable",
            "undo",
            "redo",
        ],
    },
    "extends": {
        "blockToolbar": [
            "paragraph",
            "heading1",
            "heading2",
            "heading3",
            "|",
            "bulletedList",
            "numberedList",
            "|",
            "blockQuote",
        ],
        "toolbar": [
            "heading",
            "|",
            "bold",
            "italic",
            "underline",
            "strikethrough",
            "link",
            "code",
            "subscript",
            "superscript",
            "highlight",
            "|",
            "codeBlock",
            "sourceEditing",
            "insertImage",
            "bulletedList",
            "numberedList",
            "todoList",
            "|",
            "outdent",
            "indent",
            "alignment",
            "insertTable",
            "blockQuote",
            "mediaEmbed",
            "removeFormat",
            "undo",
            "redo",
        ],
        "image": {
            "toolbar": [
                "imageTextAlternative",
                "|",
                "imageStyle:alignLeft",
                "imageStyle:alignRight",
                "imageStyle:alignCenter",
                "imageStyle:side",
                "|",
            ],
            "styles": [
                "full",
                "side",
                "alignLeft",
                "alignRight",
                "alignCenter",
            ],
        },
        "table": {
            "contentToolbar": [
                "tableColumn",
                "tableRow",
                "mergeTableCells",
                "tableProperties",
                "tableCellProperties",
            ],
            "tableProperties": {
                "borderColors": [
                    {
                        "color": "hsl(0, 0%, 0%)",
                        "label": "Black",
                    },
                    {
                        "color": "hsl(0, 75%, 60%)",
                        "label": "Red",
                    },
                    {
                        "color": "hsl(30, 75%, 60%)",
                        "label": "Orange",
                    },
                    {
                        "color": "hsl(60, 75%, 60%)",
                        "label": "Yellow",
                    },
                    {
                        "color": "hsl(90, 75%, 60%)",
                        "label": "Light green",
                    },
                    {
                        "color": "hsl(120, 75%, 60%)",
                        "label": "Green",
                    },
                ],
                "backgroundColors": [
                    {
                        "color": "hsl(0, 0%, 0%)",
                        "label": "Black",
                    },
                    {
                        "color": "hsl(0, 75%, 60%)",
                        "label": "Red",
                    },
                    {
                        "color": "hsl(30, 75%, 60%)",
                        "label": "Orange",
                    },
                    {
                        "color": "hsl(60, 75%, 60%)",
                        "label": "Yellow",
                    },
                    {
                        "color": "hsl(90, 75%, 60%)",
                        "label": "Light green",
                    },
                    {
                        "color": "hsl(120, 75%, 60%)",
                        "label": "Green",
                    },
                ],
            },
            "tableCellProperties": {
                "borderColors": [
                    {
                        "color": "hsl(0, 0%, 0%)",
                        "label": "Black",
                    },
                    {
                        "color": "hsl(0, 75%, 60%)",
                        "label": "Red",
                    },
                    {
                        "color": "hsl(30, 75%, 60%)",
                        "label": "Orange",
                    },
                    {
                        "color": "hsl(60, 75%, 60%)",
                        "label": "Yellow",
                    },
                    {
                        "color": "hsl(90, 75%, 60%)",
                        "label": "Light green",
                    },
                    {
                        "color": "hsl(120, 75%, 60%)",
                        "label": "Green",
                    },
                ],
                "backgroundColors": [
                    {
                        "color": "hsl(0, 0%, 0%)",
                        "label": "Black",
                    },
                    {
                        "color": "hsl(0, 75%, 60%)",
                        "label": "Red",
                    },
                    {
                        "color": "hsl(30, 75%, 60%)",
                        "label": "Orange",
                    },
                    {
                        "color": "hsl(60, 75%, 60%)",
                        "label": "Yellow",
                    },
                    {
                        "color": "hsl(90, 75%, 60%)",
                        "label": "Light green",
                    },
                    {
                        "color": "hsl(120, 75%, 60%)",
                        "label": "Green",
                    },
                ],
            },
        },
        "heading": {
            "options": [
                {
                    "model": "paragraph",
                    "title": "Paragraph",
                    "class": "ck-heading_paragraph",
                },
                {
                    "model": "heading1",
                    "view": "h1",
                    "title": "Heading 1",
                    "class": "ck-heading_heading1",
                },
                {
                    "model": "heading2",
                    "view": "h2",
                    "title": "Heading 2",
                    "class": "ck-heading_heading2",
                },
                {
                    "model": "heading3",
                    "view": "h3",
                    "title": "Heading 3",
                    "class": "ck-heading_heading3",
                },
            ]
        },
    },
}

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.AllowAny",
    ),
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": False,
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Newspaper API",
    "DESCRIPTION": "API CRUD newspaper Django/DRF",
    "VERSION": "1.0.0",
}

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    }
}
